// movie-web/src/components/MovieComponent.vue
<template>
  <div class="home">
    <div class="container">

      <div class="row">
        <div class="row mb-2">
          <h3 class="col-10">Phim</h3>
          <div class="col-2 text-end">
            <a href="#" class="btn btn-secondary btn-sm show-more-btn">Xem tất cả</a>
          </div>
        </div>
        <div class="row movie-list">
          <div class="col-4 movie-item" v-for="m in movie" :key="m.id">
            <router-link :to="'movie/'+m.id"  class="movie-link"><img
                :src="m.thumbnail"
                class="movie-thumbnail" alt="thumbnail"><i class="icon-play"></i><span class="movie-name">{{m.name}}</span></router-link>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex'
export default {
  data(){
    return{
    }
  },
  computed:{
    ...mapState('movie', ['movie','hotMovie']),
  },
  methods: {
    ...mapActions('movie',['fetchMovie', 'fetchMovieTopView']),

  },
  created(){
    this.fetchMovieTopView();
    this.fetchMovie();
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
a {
  color: #ccc;
}

.home {
  min-height: 90vh;
  background-color: #1a1a1a;
  padding: 48px;
  color: #ccc;

  // .show-more-btn{
  //   font-size: 16px;
  // }
  .movie-item {
    .movie-link {
      position: relative;
      display: block;
      margin: 4px;
      overflow: hidden;


      .movie-thumbnail {
        transition: all .3s ease-in-out;
        object-fit: cover;
      }

      .icon-play {
        background: #ff9601;
        height: 50px;
        width: 50px;
        position: absolute;
        top: 50%;
        left: 50%;
        margin: -25px 0 0 -25px;
        border-radius: 50%;
        opacity: 0;
        transform: scale(1.5);
        transition: all .3s ease-in-out;
      }

      .icon-play::after {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        border: 15px solid transparent;
        border-left: 20px solid #fff;
        margin: -15px 0 0 -6px;
      }

      .movie-name {
        position: absolute;
        top: 110px;
        left: 0;
        padding: 8px;
        background-color: rgba($color: #000000, $alpha: 0.7);
        min-height: 28px;
        font-size: 12px;
        width: 100%;
      }
    }
  }

  .movie-item:hover .movie-thumbnail {
    transform: scale(1.2);
  }

  .movie-item:hover .icon-play {
    transform: scale(1);
    opacity: .8;
  }




  

  .movie-list {
    .movie-item {
      .movie-link {
        height: 220px;

        .movie-thumbnail {
          height: 100%;
          width: 100%;
        }

        .movie-name {
          top: 180px;
          font-size: 16px;

        }
      }
    }
  }



}
</style>

// movie-web-nextjs/src/app/movie/page.tsx
"use client";

import styled from "styled-components";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Col, Divider, Flex, Row, Card } from "antd";
import { Content } from "antd/es/layout/layout";
import { useDispatch, useSelector } from "react-redux";
import { fecthAllMovie } from "@/features/movie/movieSlide";
import { AppDispatch, RootState } from "@/lib/store";

import StyleLayout from "@/styles/layout.module.scss";

const { Meta } = Card;
export default function MovieComponent() {
  const movies = useSelector((state: RootState) => state.movie.movies);
  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    dispatch(fecthAllMovie());
  }, [dispatch]);

  return (
    <>
      <Content>
        <Flex className={StyleLayout.lnDefaultLayout}>
          <Row className={StyleLayout.lnSection}>
            <Col span={24}>
              <TitleDividerStyled orientation="left" orientationMargin="0">
                Tất cả phim
              </TitleDividerStyled>
              <Row gutter={[16, 24]}>
                {movies.map((item, key) => (
                  <Col xs={24} sm={12} md={8} lg={8} key={key}>
                    <CardStyled
                      hoverable
                      style={{ width: "100%" }}
                      cover={
                        <>
                          <Image
                            alt={`${item.name} thumbnail`}
                            src={item.thumbnail}
                            fill
                            sizes="100%"
                          />
                          <PlayBtnStyled
                            href={`/movie/${item.slug}`}
                            className="lnBtnPlay"
                          ></PlayBtnStyled>
                        </>
                      }
                    >
                      <Meta title={item.name} />
                    </CardStyled>
                  </Col>
                ))}
              </Row>
            </Col>
          </Row>
        </Flex>
      </Content>
    </>
  );
}

const TitleDividerStyled = styled(Divider)`
  .ant-divider-inner-text {
    font-size: 24px;
    font-weight: 600;
  }
`;
const CardStyled = styled(Card)`
  .ant-card-cover {
    position: relative;
    img {
      position: relative !important;
      aspect-ratio: 4/3;
      object-fit: cover;
    }
  }
  &:hover .lnBtnPlay {
    opacity: 1;
    transform: translate(-50%, -50%) scale(1);
  }
`;
const PlayBtnStyled = styled(Link)`
  display: block;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) scale(0);
  width: 60px !important;
  height: 60px;
  background: #c51c41;
  border-radius: 100%;
  opacity: 0;
  transition: all 0.3s ease-out;

  &::before {
    content: "";
    display: block;
    position: relative;
    top: 15px;
    left: 52%;
    transform: translateX(-50%);
    width: 1px;
    height: 1px;
    border-style: solid;
    border-width: 14px 0 14px 24px;
    border-color: transparent transparent transparent #fff;
  }
`;
